POST http://localhost:8000/object HTTP/1.1
Content-Type: application/json

{
    "rid": {
        "means": "url",
        "reference": "https://hackmd.io/uUm16q1oQDmN8T0m9FABNA"
    },
    "transform": "hackmd"
}

###

POST http://localhost:8000/object

{
    "rid": "test:four",
    "action": "ingress"
}

###

POST http://localhost:8000/object/dW5kX3JlbDpISG1qbkF2eElpUjVUMlkwWWRBYzA=/read?use_base64=true

###

POST http://localhost:8000/object

{   
    "rid": "und_asrt:KlkHidvUtv8r-0o2zbHnM",
    "action": "update",
    "context": {
        "name": "Unirected Assertion",
        "members": null
    }
}

###

POST http://localhost:8000/object/

{
    "rid": "und_asrt",
    "action": "create",
    "context": {
        "name": "KOI Development Team",
        "members": [
            "agent:luke",
            "agent:orion",
            "agent:david"
        ]
    }
}

###

POST http://localhost:8000/object/und_asrt:HzwwZh0mPO-2rsYd2XpZC/read?use_b64=true
